"""
Convert PageNumbers JSON Analysis to Markdown and Word Documents

Simple script that:
1. Finds all *_WORKING_PageNumbers_analysis.json files
2. Converts them to Markdown
3. Converts them to Word documents
4. Saves in markdown_reports/ and word_reports/ folders

Output Paths:
- Markdown: /Volumes/.../PI/markdown_reports/
- Word: /Volumes/.../PI/word_reports/
"""

import json
import glob
import os
from datetime import datetime

try:
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    DOCX_AVAILABLE = True
except ImportError:
    DOCX_AVAILABLE = False
    print("⚠️  python-docx not available. Install with: pip install python-docx")


def convert_json_to_markdown(json_filepath, output_filepath):
    """Convert JSON to Markdown."""
    try:
        with open(json_filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        md_content = []
        
        # Header
        md_content.append("# Document Analysis Report (with Page Numbers)\n\n")
        md_content.append(f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        md_content.append(f"**Source Document**: `{os.path.basename(data.get('document_path', 'Unknown'))}`\n\n")
        md_content.append(f"**Total Pages**: {data.get('total_pages', 'Unknown')}\n\n")
        md_content.append(f"**Total Segments**: {data.get('total_segments', 'Unknown')}\n\n")
        md_content.append("---\n\n")
        
        # Process segments
        segments = data.get('segments', [])
        
        for segment in segments:
            segment_id = segment.get('segment_id', 'Unknown')
            page_range = segment.get('page_range', 'Unknown')
            
            md_content.append(f"## Segment: {segment_id}\n\n")
            md_content.append(f"**Pages**: {page_range}\n\n")
            
            # Names
            md_content.append("### 📋 Extracted Names\n\n")
            extracted_names = segment.get('extracted_names', [])
            if extracted_names:
                for name in extracted_names:
                    md_content.append(f"- {name}\n")
            else:
                md_content.append("*No names extracted*\n")
            md_content.append("\n")
            
            # Classifications
            md_content.append("### 🔍 Sensitive Content Classifications\n\n")
            classifications = segment.get('classifications', [])
            
            if not classifications:
                md_content.append("*No sensitive content identified*\n\n")
            else:
                md_content.append(f"**Total Classifications**: {len(classifications)}\n\n")
                
                for i, classification in enumerate(classifications, 1):
                    category = classification.get('category', 'Unknown')
                    text = classification.get('text', 'N/A')
                    page_number = classification.get('page_number', 'N/A')
                    page_range_cv = classification.get('page_range', None)
                    confidence = classification.get('confidence_score', 'N/A')
                    reason = classification.get('reason', 'N/A')
                    
                    md_content.append(f"#### Classification {i}\n\n")
                    md_content.append(f"**Category**: `{category}`\n\n")
                    
                    if page_range_cv:
                        md_content.append(f"**Page**: {page_number} (Range: {page_range_cv})\n\n")
                    else:
                        md_content.append(f"**Page**: {page_number}\n\n")
                    
                    md_content.append(f"**Confidence**: {confidence}\n\n")
                    md_content.append(f"**Content**: {text}\n\n")
                    md_content.append(f"**Reason**: {reason}\n\n")
                    md_content.append("---\n\n")
        
        # Summary
        md_content.append("## 📊 Summary\n\n")
        total_names = sum(len(seg.get('extracted_names', [])) for seg in segments)
        total_classifications = sum(len(seg.get('classifications', [])) for seg in segments)
        
        md_content.append(f"- **Total Names**: {total_names}\n")
        md_content.append(f"- **Total Classifications**: {total_classifications}\n")
        md_content.append(f"- **Total Segments**: {len(segments)}\n")
        md_content.append(f"- **Total Pages**: {data.get('total_pages', 'Unknown')}\n\n")
        
        md_content.append("---\n\n")
        md_content.append("*Report generated by Azure DI Output Parser*\n")
        
        with open(output_filepath, 'w', encoding='utf-8') as f:
            f.write(''.join(md_content))
        
        return True, data
        
    except Exception as e:
        print(f"   ❌ Markdown error: {e}")
        return False, None


def convert_json_to_word(json_data, output_filepath):
    """Convert JSON to Word document."""
    if not DOCX_AVAILABLE:
        print(f"   ⚠️  python-docx not installed")
        return False
    
    try:
        doc = Document()
        
        # Title
        title = doc.add_heading('Document Analysis Report', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Metadata
        doc.add_paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        doc.add_paragraph(f"Source: {os.path.basename(json_data.get('document_path', 'Unknown'))}")
        doc.add_paragraph(f"Total Pages: {json_data.get('total_pages', 'Unknown')}")
        doc.add_paragraph(f"Total Segments: {json_data.get('total_segments', 'Unknown')}")
        doc.add_paragraph()
        
        # Process segments
        segments = json_data.get('segments', [])
        
        for segment in segments:
            segment_id = segment.get('segment_id', 'Unknown')
            page_range = segment.get('page_range', 'Unknown')
            
            doc.add_heading(f'Segment: {segment_id}', 1)
            doc.add_paragraph(f"Pages: {page_range}")
            
            # Names
            doc.add_heading('Extracted Names', 2)
            extracted_names = segment.get('extracted_names', [])
            if extracted_names:
                for name in extracted_names:
                    doc.add_paragraph(name, style='List Bullet')
            else:
                doc.add_paragraph("No names extracted", style='Intense Quote')
            
            # Classifications
            doc.add_heading('Sensitive Content Classifications', 2)
            classifications = segment.get('classifications', [])
            
            if not classifications:
                doc.add_paragraph("No sensitive content identified", style='Intense Quote')
            else:
                doc.add_paragraph(f"Total: {len(classifications)}")
                doc.add_paragraph()
                
                for i, classification in enumerate(classifications, 1):
                    category = classification.get('category', 'Unknown')
                    text = classification.get('text', 'N/A')
                    page_number = classification.get('page_number', 'N/A')
                    page_range_cv = classification.get('page_range', None)
                    confidence = classification.get('confidence_score', 'N/A')
                    reason = classification.get('reason', 'N/A')
                    
                    doc.add_heading(f'Classification {i}', 3)
                    
                    p = doc.add_paragraph()
                    p.add_run('Category: ').bold = True
                    p.add_run(category)
                    
                    p = doc.add_paragraph()
                    p.add_run('Page: ').bold = True
                    if page_range_cv:
                        p.add_run(f"{page_number} (Range: {page_range_cv})")
                    else:
                        p.add_run(str(page_number))
                    
                    p = doc.add_paragraph()
                    p.add_run('Confidence: ').bold = True
                    p.add_run(str(confidence))
                    
                    p = doc.add_paragraph()
                    p.add_run('Content: ').bold = True
                    doc.add_paragraph(text, style='Intense Quote')
                    
                    p = doc.add_paragraph()
                    p.add_run('Reason: ').bold = True
                    doc.add_paragraph(reason, style='Intense Quote')
                    
                    doc.add_paragraph()
        
        # Summary
        doc.add_page_break()
        doc.add_heading('Summary Statistics', 1)
        
        total_names = sum(len(seg.get('extracted_names', [])) for seg in segments)
        total_classifications = sum(len(seg.get('classifications', [])) for seg in segments)
        
        doc.add_paragraph(f"Total Names: {total_names}", style='List Bullet')
        doc.add_paragraph(f"Total Classifications: {total_classifications}", style='List Bullet')
        doc.add_paragraph(f"Total Segments: {len(segments)}", style='List Bullet')
        doc.add_paragraph(f"Total Pages: {json_data.get('total_pages', 'Unknown')}", style='List Bullet')
        
        doc.save(output_filepath)
        return True
        
    except Exception as e:
        print(f"   ❌ Word error: {e}")
        return False


def main():
    """Main conversion function."""
    
    # Path
    data_path = '/Volumes/qa_datascience_convaiqa/volumes/dataanalyticslake_convai/PRISMArchives/PI/'
    
    # Find JSON files
    json_files = glob.glob(f"{data_path}*_WORKING_PageNumbers_analysis.json")
    
    if not json_files:
        print(f"❌ No JSON files found in {data_path}")
        return
    
    # Create folders
    markdown_folder = os.path.join(data_path, 'markdown_reports')
    word_folder = os.path.join(data_path, 'word_reports')
    
    os.makedirs(markdown_folder, exist_ok=True)
    os.makedirs(word_folder, exist_ok=True)
    
    print("\n" + "="*80)
    print("🚀 CONVERTING JSON TO MARKDOWN AND WORD")
    print("="*80)
    print(f"Found {len(json_files)} JSON files")
    print("="*80 + "\n")
    
    markdown_count = 0
    word_count = 0
    
    for json_file in sorted(json_files):
        filename = os.path.basename(json_file)
        print(f"📄 {filename}")
        
        base_name = filename.replace('_WORKING_PageNumbers_analysis.json', '')
        md_file = os.path.join(markdown_folder, f"{base_name}_report.md")
        word_file = os.path.join(word_folder, f"{base_name}_report.docx")
        
        # Convert to Markdown
        print(f"   📝 Creating Markdown...")
        success, json_data = convert_json_to_markdown(json_file, md_file)
        if success:
            print(f"   ✅ Markdown: {base_name}_report.md")
            markdown_count += 1
            
            # Convert to Word
            print(f"   📄 Creating Word...")
            if convert_json_to_word(json_data, word_file):
                print(f"   ✅ Word: {base_name}_report.docx")
                word_count += 1
        
        print()
    
    # Summary
    print("="*80)
    print("🎯 CONVERSION COMPLETE!")
    print("="*80)
    print(f"✅ Markdown files: {markdown_count}")
    print(f"✅ Word files: {word_count}")
    print()
    print(f"📁 Markdown: {markdown_folder}")
    print(f"📁 Word: {word_folder}")
    print("="*80)
    
    print(f"\n📍 FINAL OUTPUT PATHS:")
    print(f"   📝 Markdown: {markdown_folder}")
    print(f"   📄 Word: {word_folder}\n")


if __name__ == '__main__':
    main()

