"""
Format Final Word Documents

This script:
1. Makes titles and subtitles bold (Reason, Content, etc.)
2. Removes "Sensitive Content Classification" from each segment
3. Removes "Report generated by Azure DI Output Parser" from the end
4. Removes duplicate "Total Segments" and "Total Pages" from the beginning
5. Saves formatted documents back to final_word_reports/

Output Path:
- Formatted Word: /Volumes/.../PI/final_word_reports/
"""

import glob
import os
import shutil
import tempfile
from datetime import datetime

try:
    from docx import Document
    from docx.shared import Pt
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    DOCX_AVAILABLE = True
except ImportError:
    DOCX_AVAILABLE = False
    print("❌ python-docx not installed. Run: pip install python-docx")
    exit(1)


def format_final_word_document(input_filepath, output_filepath):
    """
    Format the final Word document with requested changes.
    
    Args:
        input_filepath: Path to input Word file
        output_filepath: Path for output Word file
    
    Returns:
        bool: Success status
    """
    try:
        # Load the document
        doc = Document(input_filepath)
        
        # Process each paragraph
        paragraphs_to_remove = []
        
        for i, paragraph in enumerate(doc.paragraphs):
            text = paragraph.text.strip()
            
            # Remove "Sensitive Content Classifications" from segments
            if text == "Sensitive Content Classifications":
                paragraphs_to_remove.append(i)
            
            # Remove "Report generated by Azure DI Output Parser" from the end
            elif text == "Report generated by Azure DI Output Parser":
                paragraphs_to_remove.append(i)
            
            # Remove duplicate "Total Segments" and "Total Pages" from beginning
            elif text.startswith("Total Segments:") or text.startswith("Total Pages:"):
                paragraphs_to_remove.append(i)
            
            # Make specific labels bold (only the labels, not the content)
            elif any(text.startswith(label) for label in [
                "Category:", "Page:", "Confidence:", "Content:", "Reason:",
                "Total Names Extracted:", "Total Classifications:",
                "Extracted Names", "Summary Statistics", "Classification Breakdown"
            ]):
                # Make only the label part bold, not the content after the colon
                if paragraph.runs:
                    # Find the colon to separate label from content
                    colon_pos = text.find(":")
                    if colon_pos > 0:
                        # Split the text at the colon
                        label_part = text[:colon_pos + 1]  # Include the colon
                        content_part = text[colon_pos + 1:].strip()  # Content after colon
                        
                        # Clear the paragraph and rebuild with bold label + normal content
                        paragraph.clear()
                        label_run = paragraph.add_run(label_part)
                        label_run.bold = True
                        label_run.font.name = 'Cambria'
                        label_run.font.size = Pt(11)
                        
                        if content_part:  # Only add content if there is content
                            content_run = paragraph.add_run(f" {content_part}")
                            content_run.font.name = 'Cambria'
                            content_run.font.size = Pt(11)
                    else:
                        # If no colon, make the whole text bold (for section headers)
                        paragraph.runs[0].bold = True
                        # Set font size to 12pt for "Summary Statistics"
                        if text == "Summary Statistics":
                            paragraph.runs[0].font.size = Pt(12)
        
        # Remove paragraphs in reverse order (to maintain indices)
        for i in sorted(paragraphs_to_remove, reverse=True):
            if i < len(doc.paragraphs):
                p = doc.paragraphs[i]
                p_element = p._element
                p_element.getparent().remove(p_element)
        
        # WORKAROUND: Save to temp file first, then copy
        with tempfile.NamedTemporaryFile(mode='wb', suffix='.docx', delete=False) as tmp_file:
            temp_path = tmp_file.name
        
        # Save to temp location
        doc.save(temp_path)
        
        # Copy to final destination
        shutil.copy2(temp_path, output_filepath)
        
        # Clean up temp file
        try:
            os.remove(temp_path)
        except:
            pass
        
        return True
        
    except Exception as e:
        print(f"   ❌ Error: {e}")
        return False


def main():
    """Main processing function."""
    
    # Paths
    data_path = '/Volumes/qa_datascience_convaiqa/volumes/dataanalyticslake_convai/PRISMArchives/PI/'
    final_folder = os.path.join(data_path, 'final_word_reports')
    
    # Check if input folder exists
    if not os.path.exists(final_folder):
        print(f"❌ Input folder does not exist: {final_folder}")
        print("   Please run remove_names_from_word_FIXED.py first to create final Word documents")
        return
    
    # Find Word files
    word_files = glob.glob(f"{final_folder}/*.docx")
    
    if not word_files:
        print(f"❌ No Word files found in {final_folder}")
        print(f"   Looking for: *.docx files")
        return
    
    print("\n" + "="*80)
    print("🚀 FORMATTING FINAL WORD DOCUMENTS")
    print("="*80)
    print(f"Processing: {final_folder}")
    print(f"Found {len(word_files)} Word files to format")
    print("="*80 + "\n")
    
    success_count = 0
    error_count = 0
    error_details = []
    
    for word_file in sorted(word_files):
        filename = os.path.basename(word_file)
        print(f"📄 Formatting: {filename}")
        
        try:
            # Process file (save back to same location)
            print(f"   ✏️  Making titles bold and removing sections...")
            if format_final_word_document(word_file, word_file):
                print(f"   ✅ Success: {filename}")
                success_count += 1
            else:
                print(f"   ❌ Failed: {filename}")
                error_count += 1
                error_details.append(filename)
        
        except Exception as e:
            print(f"   ❌ Exception: {filename} - {e}")
            error_count += 1
            error_details.append(f"{filename}: {e}")
        
        print()
    
    # Summary
    print("="*80)
    print("🎯 FORMATTING COMPLETE!")
    print("="*80)
    print(f"✅ Files formatted successfully: {success_count}")
    if error_count > 0:
        print(f"❌ Files with errors: {error_count}")
        print("Error details:")
        for detail in error_details:
            print(f"   - {detail}")
    print()
    print(f"📁 Formatted files: {final_folder}")
    print("="*80)
    
    print(f"\n📍 CHANGES MADE:")
    print(f"   ✏️  Made titles/subtitles bold (Category, Page, Confidence, Content, Reason)")
    print(f"   🗑️  Removed 'Sensitive Content Classifications' from segments")
    print(f"   🗑️  Removed 'Report generated by Azure DI Output Parser' from end")
    print(f"   🗑️  Removed duplicate 'Total Segments' and 'Total Pages' from beginning")
    print(f"   📄 All changes saved to: {final_folder}\n")


if __name__ == '__main__':
    if not DOCX_AVAILABLE:
        print("\n❌ Cannot proceed without python-docx")
        print("   Install with: pip install python-docx\n")
    else:
        main()
